# syntax=docker/dockerfile:1

FROM ruby:3.4.1

# Instalar dependências do sistema
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      libpq-dev \
      libyaml-dev \
      curl \
      nodejs \
      yarn && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Criar e definir diretório de trabalho
RUN mkdir /app
WORKDIR /app

# Copiar Gemfile e Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Instalar as gems
RUN bundle install

# Copiar todo o projeto
COPY . .

# Copiar e configurar o entrypoint
# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Expor a porta 3000
EXPOSE 3000

# Comando final para iniciar o servidor
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
